// Date: 28.12.2014 00:39:51
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.extfar.blocks.overworld.hose;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelHose extends ModelBase
{
  //fields
    ModelRenderer Center;
    ModelRenderer Corner2;
    ModelRenderer Corner3;
    ModelRenderer Corner4;
    ModelRenderer Corner1;
    ModelRenderer Top;
    ModelRenderer Bottom;

  
  public ModelHose()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Center = new ModelRenderer(this, 26, 12);
      Center.addBox(0F, 0F, 0F, 2, 2, 2);
      Center.setRotationPoint(-1F, 22F, -1F);
      Center.setTextureSize(64, 32);
      Center.mirror = true;
      setRotation(Center, 0F, 0F, 0F);
      Corner2 = new ModelRenderer(this, 22, 19);
      Corner2.addBox(0F, 0F, -7F, 2, 2, 7);
      Corner2.setRotationPoint(-1F, 22F, -1F);
      Corner2.setTextureSize(64, 32);
      Corner2.mirror = true;
      setRotation(Corner2, 0F, 0F, 0F);
      Corner3 = new ModelRenderer(this, 3, 10);
      Corner3.addBox(-7F, 0F, 0F, 7, 2, 2);
      Corner3.setRotationPoint(-1F, 22F, -1F);
      Corner3.setTextureSize(64, 32);
      Corner3.mirror = true;
      setRotation(Corner3, 0F, 0F, 0F);
      Corner4 = new ModelRenderer(this, 22, 0);
      Corner4.addBox(0F, 0F, 0F, 2, 2, 7);
      Corner4.setRotationPoint(-1F, 22F, 1F);
      Corner4.setTextureSize(64, 32);
      Corner4.mirror = true;
      setRotation(Corner4, 0F, 0F, 0F);
      Corner1 = new ModelRenderer(this, 41, 10);
      Corner1.addBox(0F, 0F, 0F, 7, 2, 2);
      Corner1.setRotationPoint(1F, 22F, -1F);
      Corner1.setTextureSize(64, 32);
      Corner1.mirror = true;
      setRotation(Corner1, 0F, 0F, 0F);
      Top = new ModelRenderer(this, 55, 16);
      Top.addBox(0F, 0F, 0F, 2, 14, 2);
      Top.setRotationPoint(-1F, 8F, -1F);
      Top.setTextureSize(64, 32);
      Top.mirror = true;
      setRotation(Top, 0F, 0F, 0F);
      Bottom = new ModelRenderer(this, 0, 20);
      Bottom.addBox(0F, 0F, 0F, 2, 5, 2);
      Bottom.setRotationPoint(-1F, 24F, -1F);
      Bottom.setTextureSize(64, 32);
      Bottom.mirror = true;
      setRotation(Bottom, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Center.render(f5);
    Corner2.render(f5);
    Corner3.render(f5);
    Corner4.render(f5);
    Corner1.render(f5);
    Top.render(f5);
    Bottom.render(f5);

  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  public void renderCenter()
  {
	  float f5 = 0.0625F;
	  Center.render(f5);
  }
  
  public void renderCross() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner2.render(f5);
    Corner3.render(f5);
    Corner4.render(f5);
    Corner1.render(f5);
  }
  
  public void renderSide1() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner1.render(f5);
  }
  public void renderSide2() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner2.render(f5);
  }
  public void renderSide3() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner3.render(f5);
  }
  public void renderSide4() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner4.render(f5);
  }
  
  public void renderCorner1() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner2.render(f5);
    Corner1.render(f5);
  }
  public void renderCorner2() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner2.render(f5);
    Corner3.render(f5);
  }
  public void renderCorner3() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner3.render(f5);
    Corner4.render(f5);
  }
  public void renderCorner4() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner4.render(f5);
    Corner1.render(f5);
  }
  
  public void renderLine1() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner3.render(f5);
    Corner1.render(f5);
  }
  public void renderLine2() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner2.render(f5);
    Corner4.render(f5);
  }
  
  public void renderTCross1() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner2.render(f5);
    Corner1.render(f5);
    Corner3.render(f5);
  }
  public void renderTCross2() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner2.render(f5);
    Corner3.render(f5);
    Corner4.render(f5);
  }
  public void renderTCross3() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner3.render(f5);
    Corner1.render(f5);
    Corner4.render(f5);
  }
  public void renderTCross4() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner2.render(f5);
    Corner1.render(f5);
    Corner4.render(f5);
  }

  
  
  //Now with a top
  public void renderCenterT()
  {
	  float f5 = 0.0625F;
	  Center.render(f5);
	  Top.render(f5);
  }
  
  public void renderCrossT() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner2.render(f5);
    Corner3.render(f5);
    Corner4.render(f5);
    Corner1.render(f5);
	  Top.render(f5);

  }
  
  public void renderSide1T() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner1.render(f5);
	  Top.render(f5);

  }
  public void renderSide2T() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner2.render(f5);
	  Top.render(f5);

  }
  public void renderSide3T() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner3.render(f5);
	  Top.render(f5);

  }
  public void renderSide4T() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner4.render(f5);
	  Top.render(f5);

  }
  
  public void renderCorner1T() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner2.render(f5);
    Corner1.render(f5);
	  Top.render(f5);

  }
  public void renderCorner2T() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner2.render(f5);
    Corner3.render(f5);
	  Top.render(f5);

  }
  public void renderCorner3T() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner3.render(f5);
    Corner4.render(f5);
	  Top.render(f5);

  }
  public void renderCorner4T() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner4.render(f5);
    Corner1.render(f5);
	  Top.render(f5);

  }
  
  public void renderLine1T() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner3.render(f5);
    Corner1.render(f5);
	  Top.render(f5);

  }
  public void renderLine2T() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner2.render(f5);
    Corner4.render(f5);
	  Top.render(f5);

  }
  
  public void renderTCross1T() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner2.render(f5);
    Corner1.render(f5);
    Corner3.render(f5);
	  Top.render(f5);

  }
  public void renderTCross2T() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner2.render(f5);
    Corner3.render(f5);
    Corner4.render(f5);
	  Top.render(f5);

  }
  public void renderTCross3T() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner3.render(f5);
    Corner1.render(f5);
    Corner4.render(f5);
	  Top.render(f5);

  }
  public void renderTCross4T() 
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner2.render(f5);
    Corner1.render(f5);
    Corner4.render(f5);
	  Top.render(f5);

  }
  
  public void renderBottom1()
  {
  	float f5 = 0.0625F;
    Center.render(f5);
    Corner1.render(f5);
    Bottom.render(f5);
  }

}
